import "./globals.css";
import Topo from "@/componentes/Topo";

export const metadata = {
  title: "Curso Rotas - Exemplo Prátoco",
  description: "Generated by create next app",
  robots: 'index, follow',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topo/>
        {children}
      </body>
    </html>
  );
}
